### ISSUE TITLE
Test case numbering off by 1 and "Submission rejected" message even though accepted

### ISSUE THREAD

**Issue by karlek** [EmilGedda/hattis#1]
For kattis problem with a point system, hattis reports testcases with an off by one (3 of 2) and submission rejected message even though it was accepted. 
![out20121](https://cloud.githubusercontent.com/assets/1278705/20053869/c2f97caa-a4da-11e6-990d-a977606faf74.png)

**Comment by EmilGedda** [comment]
This should be a one-line fix (hopefully) since hattis does not expect numbers in the status message from Kattis. I don't have a ready-to-submit solution for a problem with a point system, so I won't be able to test this a 100% (unless I find a really simple point based problem to solve), but hopefully a fix will be ready for 1.1

All the off by one errors displayed are simply due to me not being able to count somehow.

**Comment by karlek** [comment]
I can supply you with one. Will send you one on slack @ mottagningen
