### ISSUE TITLE
Prelude.read: no parse for non-existing problems

### ISSUE THREAD

**Issue by karlek** [EmilGedda/hattis#4]
When submitting to a non-existent problem hattis returns `Prelude.read: no parse`.

This could have a more descriptive error message. This can happen since some challenges exists only on `kth@kattis` and are missing on `open@kattis`. Gave me a headache when I used the wrong `kattisrc` file.

![out11742](https://cloud.githubusercontent.com/assets/1278705/20054267/806e45bc-a4dc-11e6-9ecc-4df7e7a71622.png)

**Comment by EmilGedda** [comment]
I've been contemplating on how to fix this correctly, whether to check against a global database or whether to check the result of the submission for error (which is the more resonable choice). The global database-thing is pretty handy with autocomplete but with 1.1 and Makefile-generation submitting repeatedly should be as easy as writing "make".
But this is definitely a bug and I'll get right to it.

I haven't tested hattis at all on problems on `open@kattis`, since there exists legit zero information about anything API-related (or maybe I've simply missed it) on how the open and kth-version of kattis interacts such as sessions, parsing and all that stuff. Currently hattis only 'officially' supports `kth@kattis` and it will probably be like that until I've more time on my hands.

**Comment by karlek** [comment]
If it is possible, I would say that it's best to parse the submission response. Do you have a sample output for these kinds of requests?

Parsing the submission response is easier and won't need the extra functionality for a global database. Since many new problems arise for the clients such as updating, parsing the problems from the submit page, using different databases for `open@kattis` and `kth@kattis`. Might be fun to write the code though and would be really cool, like correcting typos: `Problem: factorin doesn't exist, did you mean "factoring"`? The database might be a 1.2 feature 😉 

I actually mailed kattis a few years back when I made my Sublime plugin for the kattis submit script. I also wanted the autocomplete feature for the problems. The answered that they didn't have an API and asked me to write what I wanted. Then they didn't reply... At least they have now added a autocomplete field for submissions on http://kth.kattis.com/submit which you can extract all the problem names and ids from.

**Comment by EmilGedda** [comment]
The typo-correcting stuff sounds like a really good idea, I'll add it to my todo-list.
1951d1f now implements the parsing of a submission-attempt which was surprisingly simple and displays a somewhat helpful error message.
